---
title: Consolidated pathway analysis using customized GMT 
author:
  - name: Shuai Yuan
    url: https://www.straublab.pitt.edu/lab/
    address: University of Pittsburgh
    email: yuans@pitt.edu
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 5
    number_sections: true
    self_contained: yes
---

```{r setup, echo = FALSE, warning=FALSE}
library(ragg)
# library(Cairo)

# ragg_png = function(...) {
#   ragg::agg_png(..., res = 300, units = "in")
# }

options(
  htmltools.dir.version = FALSE, 
  knitr.duplicate.label = "allow", 
  DT.options = list(scrollX = TRUE), 
  scipen = 999
  # bitmapType = "cairo"
  )
knitr::opts_chunk$set(
  # dev = "CairoPNG",
  # units = "in",
  dev = "agg_png",
  fig.ext = "png",
  dev.args=list(res = 300, units = "in"), 
  dpi = 96,
  out.width = "100%",
  cache = FALSE,
  echo = FALSE,
  message = TRUE, 
  warning = TRUE,
  hiline = TRUE
  )

set.seed(123)
```

```{r}
library(org.Hs.eg.db)
library(clusterProfiler)
library(tidyverse)

source("library_builder/build_go_regulation_gmt.R")
```

# Load signed and unsigned libraries

```{r}
signed_lib_list <- list.files("pathway_library/", pattern = ".*_signed.*\\.gmt$", full.names = TRUE)
unsigned_lib_list <- list.files("pathway_library/", pattern = "\\.gmt$", full.names = TRUE)
unsigned_lib_list <- unsigned_lib_list[!unsigned_lib_list %in% signed_lib_list]

signed_lib <- map(signed_lib_list, function(x){
  lib_name <- basename(x) %>%
    str_replace("\\.gmt", "")
  df_term2gene <- read.gmt(x)
  df_term2name <- read_gmt_term2name(x)
  list(
    lib_name = lib_name, 
    term2gene = df_term2gene, 
    term2name = df_term2name
  )
})

unsigned_lib <- map(unsigned_lib_list, function(x){
  lib_name <- basename(x) %>%
    str_replace("\\.gmt", "")
  df_term2gene <- read.gmt(x)
  df_term2name <- read_gmt_term2name(x)
  list(
    lib_name = lib_name, 
    term2gene = df_term2gene, 
    term2name = df_term2name
  )
})
```

# Wrapper functions to run ORA and GSEA by iterating through signed rank lists


```{r}
run_ora <- function(signed_rank, top_frac_threshold = 0.1, org_db, universe=NULL, signed_library, unsigned_library, pvalueCutoff=1, qvalueCutoff=1, pAdjustMethod = "BH", minGSSize = 15, maxGSSize = 500) {
  if (is.null(universe)) universe <- names(signed_rank)
  
  # gene selection strategy: select top 10% genes by abs(stat) and split them into up and down genes.
  # top_frac_threshold <- 0.1
  
  unsigned_rank <- sort(abs(signed_rank), decreasing = TRUE)
  
  unsigned_entrezids <- names(unsigned_rank)[unsigned_rank > quantile(unsigned_rank, 1-top_frac_threshold)]
  
  up_entrezids <- names(signed_rank)[signed_rank > 0 & names(signed_rank) %in% unsigned_entrezids]
  down_entrezids <- names(signed_rank)[signed_rank < 0 & names(signed_rank) %in% unsigned_entrezids]

  df_ora_signed <- map_dfr(signed_library, function(x){
  df_ora_up <- enricher(
    gene = up_entrezids,
    universe = universe, 
    TERM2GENE = x[["term2gene"]], 
    TERM2NAME = x[["term2name"]], 
    pvalueCutoff = pvalueCutoff, 
    qvalueCutoff = qvalueCutoff, 
    pAdjustMethod = "none",
    minGSSize = minGSSize,
    maxGSSize = maxGSSize 
  )
  
  if (!is.null(df_ora_up)) {
    df_ora_up <- df_ora_up %>%
      setReadable(org_db, "ENTREZID") %>%
      as.data.frame() %>%
      mutate(
        Direction = "up", 
        Library = x[["lib_name"]]
      ) %>%
      select(Library, Direction, head(names(.), -2)) %>%
      arrange(pvalue)
    row.names(df_ora_up) <- NULL
    }

  df_ora_down <- enricher(
    gene = down_entrezids,
    universe = universe, 
    TERM2GENE = x[["term2gene"]], 
    TERM2NAME = x[["term2name"]], 
    pvalueCutoff = pvalueCutoff, 
    qvalueCutoff = qvalueCutoff, 
    pAdjustMethod = "none",
    minGSSize = minGSSize,
    maxGSSize = maxGSSize 
  )
  
  if (!is.null(df_ora_down)) {
    df_ora_down <- df_ora_down %>%
      setReadable(org_db, "ENTREZID") %>%
      as.data.frame() %>%
      mutate(
        Direction = "down", 
        Library = x[["lib_name"]]
      ) %>%
      select(Library, Direction, head(names(.), -2)) %>%
      arrange(pvalue)
    row.names(df_ora_down) <- NULL
    }

  bind_rows(df_ora_up, df_ora_down)
  })
  
  df_ora_unsigned <- map_dfr(unsigned_library, function(x){
    df_ora_unsigned <- enricher(
      gene = unsigned_entrezids,
      universe = universe,
      TERM2GENE = x[["term2gene"]],
      TERM2NAME = x[["term2name"]],
      pvalueCutoff = pvalueCutoff,
      qvalueCutoff = qvalueCutoff,
      pAdjustMethod = "none",
      minGSSize = minGSSize,
      maxGSSize = maxGSSize
    )
  
    if (!is.null(df_ora_unsigned)) {
      df_ora_unsigned <- df_ora_unsigned %>%
        setReadable(org_db, "ENTREZID") %>%
        as.data.frame() %>%
        mutate(
          Direction = "unsigned",
          Library = x[["lib_name"]]
        ) %>%
        select(Library, Direction, head(names(.), -2)) %>%
        arrange(pvalue)
      row.names(df_ora_unsigned) <- NULL
      }
  
    df_ora_unsigned
  })
  
  df_ora <- bind_rows(df_ora_signed, df_ora_unsigned) %>%
    group_by(Library, Direction) %>%
    mutate(
      p.adjust = p.adjust(pvalue, method = pAdjustMethod)
    )
}
```



```{r}
run_gsea <- function(signed_rank, org_db, signed_library, unsigned_library,
                    pvalueCutoff=1, pAdjustMethod = "BH", minGSSize = 15, maxGSSize = 500){
  unsigned_rank <- sort(abs(signed_rank), decreasing = TRUE)
  
  df_gsea_signed <- map_dfr(signed_library, function(x){
    df_gsea <- GSEA(
      geneList = signed_rank,
      TERM2GENE = x[["term2gene"]],
      TERM2NAME = x[["term2name"]],
      pvalueCutoff = pvalueCutoff,
      pAdjustMethod = "none", 
      minGSSize = minGSSize,
      maxGSSize = maxGSSize, 
      eps = 0, 
      nPermSimple = 10000, 
      seed = TRUE
    )
    
    if (!is.null(df_gsea)) {
    df_gsea <- df_gsea %>%
      setReadable(org_db, "ENTREZID") %>%
      as.data.frame() %>%
      mutate(
        Direction = "signed", 
        Library = x[["lib_name"]]
      ) %>%
      select(Library, Direction, head(names(.), -2)) %>%
      arrange(pvalue)
    row.names(df_gsea) <- NULL
    df_gsea
    }
  })
  
  df_gsea_unsigned <- map_dfr(unsigned_library, function(x){
    df_gsea <- GSEA(
      geneList = unsigned_rank,
      TERM2GENE = x[["term2gene"]],
      TERM2NAME = x[["term2name"]],
      pvalueCutoff = pvalueCutoff,
      pAdjustMethod = "none", 
      minGSSize = minGSSize,
      maxGSSize = maxGSSize,
      eps = 0, 
      nPermSimple = 10000,  
      scoreType = "pos", 
      seed = TRUE
    )
    
  if (!is.null(df_gsea)) {
    df_gsea <- df_gsea %>%
      setReadable(org_db, "ENTREZID") %>%
      as.data.frame() %>%
      mutate(
        Direction = "unsigned", 
        Library = x[["lib_name"]]
      ) %>%
      select(Library, Direction, head(names(.), -2)) %>%
      arrange(pvalue)
    row.names(df_gsea) <- NULL
    df_gsea
    }
  })
  
  # browser()
  df_gsea <- bind_rows(df_gsea_signed, df_gsea_unsigned) %>%
    group_by(Library, Direction) %>%
    mutate(
      p.adjust = p.adjust(pvalue, method = pAdjustMethod)
    )
}

# df_gsea <- run_gsea(signed_rank, org.Hs.eg.db, signed_lib, unsigned_lib)
```

# Loop through DEG files and perform pathway analysis

```{r}
deg_files <- list.files("../data/transcriptomics/", pattern = "deg.csv", recursive = TRUE, full.names = TRUE)

for (f in deg_files){
  dataset_name <- basename(dirname(f))
  
  df_deg <- read.csv(f)
  names(df_deg) <- gsub("^t$", "stat", names(df_deg))
  
  for (contr in unique(df_deg$contrast)){
    signed_rank <- df_deg %>%
      filter(contrast == contr) %>%
      filter(!duplicated(GeneID) & !is.na(GeneID)) %>%
      arrange(desc(stat)) %>%
      pull(stat, name = GeneID)
    
    df_ora <- run_ora(signed_rank, org_db = org.Hs.eg.db, signed_library = signed_lib, unsigned_library = unsigned_lib)
    df_gsea <- run_gsea(signed_rank, org.Hs.eg.db, signed_lib, unsigned_lib)
    
    out_dir <- file.path("output", dataset_name)
    dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)
    write.csv(df_ora, file.path(out_dir, sprintf("%s_%s_ora.csv", dataset_name, contr)), row.names = FALSE)
    write.csv(df_gsea, file.path(out_dir, sprintf("%s_%s_gsea.csv", dataset_name, contr)), row.names = FALSE)
  }
}
```

# Yurdagul SMC media proteomics

```{r}
dataset_name <- "yurdagul_smc_odc1kd_media"
  
df_de <- read.csv("../data/proteomics/yurdagul_lab/de.csv")
  
for (contr in unique(df_de$contrast)){
  df_de_sub <- df_de %>%
    mutate(
      Entrezid = mapIds(org.Hs.eg.db, keys = ID, column = "ENTREZID", keytype = "UNIPROT")
    ) %>%
    filter(contrast == contr) %>% 
    filter(!duplicated(Entrezid) & !is.na(Entrezid)) %>%
    filter(!is.na(t))
  
  universe <- df_de_sub$Entrezid
  
  sig_signed_rank <- df_de_sub %>%
    filter(adj.P.Val < 0.05) %>% 
    arrange(desc(t)) %>%
    pull(t, name = Entrezid)
  
  df_ora <- run_ora(sig_signed_rank, top_frac_threshold = 1, universe = universe, org_db = org.Hs.eg.db, signed_library = signed_lib, unsigned_library = unsigned_lib)
  
  signed_rank <- df_de_sub %>%
    arrange(desc(t)) %>%
    pull(t, name = Entrezid)
  
  df_gsea <- run_gsea(signed_rank, org.Hs.eg.db, signed_lib, unsigned_lib)
  
  out_dir <- file.path("output", dataset_name)
  dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)
  write.csv(df_ora, file.path(out_dir, sprintf("%s_%s_ora.csv", dataset_name, contr)), row.names = FALSE)
  write.csv(df_gsea, file.path(out_dir, sprintf("%s_%s_gsea.csv", dataset_name, contr)), row.names = FALSE)
}

```


# **Appendix**

## **Session Info**

This markdown file was generated using R with the following environment. 

```{r}
sessionInfo()
```
